import { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import Button from '../../components/common/Button';
import Header from '../../components/common/Header';
import type { AuthStackParamList } from '../../navigation/types';
type Props=NativeStackScreenProps<AuthStackParamList,'Onboarding'>;
const interests=[['diabetes','Diabetes','Glucosa, HbA1C e insulina'],['cardio','Salud cardiovascular','Colesterol y triglicéridos'],['renal','Función renal','Creatinina y urea'],['general','Salud general','Vitaminas y hemograma']];
export default function OnboardingScreen({navigation}:Props){const [selected,setSelected]=useState<string[]>([]);const toggle=(id:string)=>setSelected(current=>current.includes(id)?current.filter(x=>x!==id):[...current,id]);return <SafeAreaView style={s.page}><Header title="Preferencias" onBack={navigation.canGoBack()?()=>navigation.goBack():undefined}/><ScrollView contentContainerStyle={s.content}><Text style={s.title}>¿Qué deseas monitorear?</Text><Text style={s.subtitle}>Selecciona uno o más intereses de salud.</Text>{interests.map(([id,title,subtitle])=>{const active=selected.includes(id);return <Pressable key={id} style={[s.card,active&&s.active]} onPress={()=>toggle(id)}><View style={s.body}><Text style={s.cardTitle}>{title}</Text><Text style={s.cardSubtitle}>{subtitle}</Text></View><View style={[s.check,active&&s.checkActive]}>{active&&<Text style={s.checkText}>✓</Text>}</View></Pressable>})}</ScrollView><View style={s.footer}><Button title="Continuar" disabled={!selected.length} onPress={()=>navigation.navigate('Login')}/></View></SafeAreaView>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#EDF3FF'},content:{padding:20},title:{fontSize:30,fontWeight:'800',color:'#243449'},subtitle:{marginTop:8,marginBottom:25,fontSize:16,color:'#8B97A9'},card:{backgroundColor:'#FFF',borderRadius:18,padding:16,marginBottom:14,flexDirection:'row',alignItems:'center',borderWidth:1,borderColor:'#E8EDF5'},active:{borderColor:'#2F6CF0',backgroundColor:'#F8FAFF'},body:{flex:1},cardTitle:{fontSize:15,fontWeight:'800',color:'#2B394D'},cardSubtitle:{marginTop:4,fontSize:12,color:'#92A0B3'},check:{width:24,height:24,borderRadius:12,borderWidth:1.5,borderColor:'#CCD5E3'},checkActive:{backgroundColor:'#2F6CF0',borderColor:'#2F6CF0',justifyContent:'center',alignItems:'center'},checkText:{color:'#FFF',fontWeight:'800'},footer:{padding:20}});
